[package]
name = "omic"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.72"
clap = { version = "4.3.21", features = ["derive"] }
tracing-subscriber = "0.3.17"
tracing = "0.1.37"

omicd = { path = "../omicd" }
