name: android
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "./omic-android"
      - ".github/workflows/android.yml"

jobs:
  build:
    defaults:
      run:
        working-directory: "./omic-android"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assemble --no-daemon

      - name: Rename APK
        run: tree

      - name: Rename APK
        run: mv ./app/build/outputs/apk/release/app-release.apk omic.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: omic-android
          path: omic.apk
