name: android
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    defaults:
      run:
        working-directory: "./omic-android"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: gradle

      - name: Update repos
        run: sudo apt-get update -y

      - name: Install sdkmanager
        run: sudo apt-get install -y sdkmanager

      - name: Install NDK
        run: yes | sdkmanager "ndk;26.1.10909125"

      - name: Install zipalign
        run: sudo apt-get install -y zipalign

      - name: Install apksigner
        run: sudo apt-get install -y apksigner

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assemble --no-daemon

      - name: Rename APK
        run: mv ./app/build/outputs/apk/release/app-release.apk omic.apk

      - name: Decode Keystore
        run: echo ${{secrets.KS}} | base64 --decode > keystore.jks

      - name: ZipAlign
        run: zipalign -v -p 4 omic.apk omic-aligned.apk

      - name: Sign .apk
        run: apksigner sign --ks keystore.jks --ks-key-alias "key0" --ks-pass "pass:${{secrets.PSK}}" --key-pass "pass:${{secrets.PSK}}" --out omic-signed.apk omic-aligned.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: omic-android
          path: omic-android/omic-signed.apk
