name: omic
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths-ignore:
      - "./omic-android"
      - ".github/workflows/android.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: sudo apt update
      - name: Install dependencies
        run: sudo apt install clang llvm libclang-dev libpipewire-0.3-dev libspa-0.2-dev libgtk-4-dev libpango1.0-dev libspa-0.2-modules

      - uses: actions/checkout@v3
      - uses: Accurate0/rust-toolchain@main
        with:
          profile: minimal
          toolchain: stable

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: cargo build
        run: cargo build --locked --profile release-strip

      - name: copy artifacts
        run: |
          mkdir ./omic
          cp ./target/release-strip/omic ./omic
          cp ./target/release-strip/omic-gtk ./omic
          cp ./target/release-strip/omicd ./omic

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: omic
          path: ./omic
